[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
  "-c",
  "pnpm tailwindcss build -i web_frontend/src/tailwind.css -o web_frontend/dist/.stage/tailwind.css",
]
