name: Update filters

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-filters:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - name: "Install dependencies"
        working-directory: "./filters"
        run: python3 -m pip install -r requirements.txt
      - name: Update filters
        working-directory: "./filters"
        run: python3 main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: "filters/registry"
          author_name: "Privaxy [bot]"
          author_email: "bot@privaxy.net"
          branch: "main"
          message: "Update filters"
